event_inherited();
scene_info =
[
	[scene_make_player_static],
	[scene_textbox,Text("boss: feeling")],
	[scene_move_object,global.oPlayer,boss_spawn_x - 150,global.oPlayer.spd],
	[scene_wait,0.5],
	[scene_next_take_live_args],
	[
		scene_create_effect,
		function(){return global.oPlayer.x},	
		function(){return global.oPlayer.y - global.oPlayer.view_y_offset - global.oPlayer.worry_y_offset},
		global.oPlayer.worry_sprite,
		1,
		false
	],
	[scene_wait,0.5],
	[scene_create_object,boss_spawn_x,FLOOR_Y-boss_dist_to_floor,"Instances",obj_boss],
	[scene_boss_shader_transition,boss_idle_form_enum],
	[scene_candles_fire_extinguish],
	[scene_textbox,Text("boss: appears")],
	[scene_textbox,Text("boss: explanation")],
	[scene_textbox,Text("boss: don't fear")],
	[scene_change_camera_target,obj_boss],
	[scene_wait,0.1],
	[scene_animate_object,obj_boss,spr_boss_tornado_transition,noone],
	[scene_boss_earthquake],
	[scene_wait,0.1],
	[scene_change_camera_target,global.oPlayer],
	[scene_move_object,global.oPlayer,shrine_x,global.oPlayer.spd],
	[scene_crystal_detach],
	[scene_wait,0.5],
	[scene_object_animate,global.oPlayer,spr_hero_sever_lifestream_start,noone,noone,false,OBJECT_ANIM_END_MODE.STATIC],
	[scene_change_object_sprite,global.oPlayer,spr_hero_sever_lifestream_static,true],
	[scene_textbox,Text("boss: hide crystal")],
	[scene_textbox,Text("boss: sever lifestreams")],
	[scene_animate_object,global.crystal,spr_crystal_explode],
	[scene_crystal_sever_lifestream],
	[scene_wait,0.5],
	[scene_change_camera_target,global.oPlayer],
	[scene_wait_no_skip,0.5],
	[scene_boss_fight_wall_barriers_move,1.5],
	[scene_wait,0.2],
	[scene_object_animate,global.oPlayer,spr_hero_sever_lifestream_end,noone,noone,false,OBJECT_ANIM_END_MODE.STATIC],
	[scene_wait,0.5],
	[scene_crystal_hide_underground],
	[scene_wait,0.7],
	[scene_freeup_companion_soul],
	[scene_wait,0.1],
	[scene_change_camera_target,obj_companion_soul],
	[scene_boss_wait_for_companion_soul],
	[scene_wait,0.5],
	[scene_boss_destroy_companion_soul],
	[scene_wait,3],
	[scene_change_camera_target,global.oPlayer],
	[scene_wait,1],
	[scene_textbox,Text("boss: soul death")],
	[scene_textbox,Text("boss: fight now")]
]

